Fix consistent (?) timing every 10 seconds
Performance is very disappointing in the rust version.

Python:

    $ time python3 nats2jetstream.py -c nats2jetstream.ini
    nats2jetstream (pids=[68054 -> 68053])
    nats2jetstream: <Stats: run_input_nats 3091 msgs (309.165 msg/s, 0.435 ms/msg)>
    nats2jetstream: <Stats: run_sink_jetstream 3034 msgs (303.429 msg/s, 0.899 ms/msg)>
    nats2jetstream: <Stats: run_input_nats 9161 msgs (916.098 msg/s, 0.558 ms/msg)>
    nats2jetstream: <Stats: run_sink_jetstream 9218 msgs (921.801 msg/s, 0.604 ms/msg)>
    nats2jetstream: <Stats: run_input_nats 18 msgs (1.800 msg/s, 0.003 ms/msg)>
    nats2jetstream: <Stats: run_sink_jetstream 18 msgs (1.800 msg/s, 0.924 ms/msg)>
    nats2jetstream: <Stats: run_sink_jetstream 3226 msgs (322.601 msg/s, 0.876 ms/msg)>
    nats2jetstream: <Stats: run_input_nats 3285 msgs (328.500 msg/s, 0.620 ms/msg)>
    nats2jetstream: <Stats: run_sink_jetstream 9307 msgs (930.695 msg/s, 0.593 ms/msg)>
    nats2jetstream: <Stats: run_input_nats 9248 msgs (924.794 msg/s, 0.538 ms/msg)>
    nats2jetstream: <Stats: run_input_nats 18 msgs (1.800 msg/s, 0.003 ms/msg)>
    nats2jetstream: <Stats: run_sink_jetstream 18 msgs (1.800 msg/s, 0.969 ms/msg)>
    nats2jetstream: <Stats: run_input_nats 54 msgs (5.400 msg/s, 0.002 ms/msg)>
    nats2jetstream: <Stats: run_sink_jetstream 54 msgs (5.400 msg/s, 0.803 ms/msg)>

    ^Cerror: nats2jetstream:  (KeyboardInterrupt)
    nats2jetstream: <Stats: run_input_nats 0 msgs (0.000 msg/s, 0.000 ms/msg)>
    nats2jetstream: <Stats: run_sink_jetstream 0 msgs (0.000 msg/s, 0.000 ms/msg)>
    error: run_sink_jetstream:  (KeyboardInterrupt): <Stats: run_sink_jetstream 0 msgs (0.000 msg/s, 0.000 ms/msg)>
    error: <producer>:  (KeyboardInterrupt)
    EOF consumer_died 512 768

    real    1m11.875s
    user    0m6.485s
    sys     0m0.928s

Rust:

    (various slow times and not sure whether consuming or not..)
    ...
    info: 0 items, 10 secs, 0.000 msg/sec, 0.000 msec/msg (pub)
    info: 38 items, 10 secs, 3.800 msg/sec, 4.737 msec/msg (pub)
    info: 835 items, 125 secs, 6.680 msg/sec, 148.823 msec/msg (pub)
    info: 1973 items, 10 secs, 197.300 msg/sec, 5.070 msec/msg (pub)
    info: 1972 items, 10 secs, 197.200 msg/sec, 5.073 msec/msg (pub)
    info: 1972 items, 10 secs, 197.200 msg/sec, 5.071 msec/msg (pub)
    info: 1971 items, 10 secs, 197.100 msg/sec, 5.073 msec/msg (pub)
    info: 1972 items, 10 secs, 197.200 msg/sec, 5.073 msec/msg (pub)
    info: 1971 items, 10 secs, 197.100 msg/sec, 5.075 msec/msg (pub)
    info: 1969 items, 10 secs, 196.900 msg/sec, 5.078 msec/msg (pub)
    info: 1971 items, 10 secs, 197.100 msg/sec, 5.074 msec/msg (pub)
    ^C
    real    6m52.639s
    user    0m0.891s
    sys     0m1.344s

So, user time is nice. But way more important is the publish time, which
is 5ms, instead of 0.5ms.

Also, where is the consistent timing?